Repository sanika391/SpoonShare, pull requests merged in 2024-05, with the labels that each got.

#21 Solved ui overflow issues in donate page,recycle page and dashboard page
  lib/screens/dashboard/dashboard_page.dart
  lib/screens/donate/donate_page.dart
  lib/screens/recycle/recycle.dart
  pubspec.lock
Labels: (gssoc), (Level2)

#25 Fixed video embedding problem in README.md file
  README.md
Labels: (gssoc)

#43 Render Flex Resolved in onboarding and signup screen
  lib/onboarding.dart
  lib/screens/auth/signup.dart
Labels: (gssoc), level1

#42 bottom pixel overflow removed
  lib/onboarding.dart
Labels: (gssoc), level1

#20 PULL-REQUEST-TEMPLATE-#19
  .github/ISSUE_TEMPLATE/pull_request_report.md
Labels: (gssoc)

#47 fixed UI Overflow in share free food
  android/app/build.gradle
  lib/screens/donate/share_food.dart
  lib/splash_screen.dart
Labels: bug, level1

#66 Completed Google Map integration in Food Donating page
  lib/screens/donate/donate_food.dart
  pubspec.lock
Labels: enhancement, good first issue, level1

#65 Solved UI overflow issues
  lib/main.dart
  lib/screens/dashboard/dashboard_page.dart
  lib/screens/donate/donate_page.dart
Labels: (gssoc), level1

#74 Auto comment on opened PR and merged or closed PR
  .github/workflows/autocomment-pr-closed.yml
  .github/workflows/autocomment-pr-merge.yml
Labels: enhancement, (gssoc), level1
