Repository sanika391/SpoonShare, pull requests merged in 2024-06, with the labels that each got.

#79 Issue #78 DependaBot Added
  .github/dependabot.yaml
Labels: enhancement, level1, gssoc

#91 Implement Photo Evaluation Feature for SpoonShare App, issue no #90
  lib/screens/donate/donate_food.dart
  lib/screens/donate/share_food.dart
  lib/screens/recycle/pickup_food.dart
  lib/utils/extract_exif_data.dart
  pubspec.lock
  pubspec.yaml
Labels: good first issue, level2, gssoc

#99 Integrated Dockerfile in the project
  Dockerfile
  README.md
  docker-compose.yml
  pubspec.lock
Labels: enhancement, level2, gssoc
